// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCL.Data;

#nullable disable

namespace NCL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NCL.Shared.Entities.Class", b =>
                {
                    b.Property<int>("Class__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Class__ID"));

                    b.Property<int>("Class_Page__ID")
                        .HasColumnType("int");

                    b.Property<string>("Class__FolderPathName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class__Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Class__SequenceNo")
                        .HasColumnType("int");

                    b.Property<int?>("Page__ID")
                        .HasColumnType("int");

                    b.HasKey("Class__ID");

                    b.HasIndex("Page__ID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Employee", b =>
                {
                    b.Property<int>("Employee__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee__ID"));

                    b.Property<DateTime?>("Employee__Log")
                        .HasColumnType("datetime2");

                    b.Property<string>("Employee__Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employee__ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Event", b =>
                {
                    b.Property<int>("Event__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Event__ID"));

                    b.Property<int?>("Class__ID")
                        .HasColumnType("int");

                    b.Property<int>("Event_Class__ID")
                        .HasColumnType("int");

                    b.Property<string>("Event__Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event__FileDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event__FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Event__FileSequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Event__FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event__FolderPathName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Event__SequenceNo")
                        .HasColumnType("int");

                    b.Property<bool>("Event__Thumbnail")
                        .HasColumnType("bit");

                    b.Property<string>("Event__Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Event__ID");

                    b.HasIndex("Class__ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Location", b =>
                {
                    b.Property<int>("Location__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Location__ID"));

                    b.Property<string>("Location__Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Location__ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Moment", b =>
                {
                    b.Property<int>("Moment__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Moment__ID"));

                    b.Property<int>("EmployeeEmployee__ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Moment__DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moment__Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moment__FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moment__FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Moment__SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Moment__Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moment__Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Moment__ID");

                    b.HasIndex("EmployeeEmployee__ID");

                    b.ToTable("Moments");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Page", b =>
                {
                    b.Property<int>("Page__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Page__ID"));

                    b.Property<string>("Page__FolderPathName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page__Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page__SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Page__SequenceNo")
                        .HasColumnType("int");

                    b.HasKey("Page__ID");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Video", b =>
                {
                    b.Property<int>("Video__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Video__ID"));

                    b.Property<int>("LocationLocation__ID")
                        .HasColumnType("int");

                    b.Property<string>("Video__Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video__Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Video__ID");

                    b.HasIndex("LocationLocation__ID");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Visitor", b =>
                {
                    b.Property<int>("Visitor__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Visitor__ID"));

                    b.Property<string>("Visitor__Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visitor__Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Visitor__ID");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("NCL.Shared.Entities.VisitorActivity", b =>
                {
                    b.Property<int>("VisitorActivity__ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorActivity__ID"));

                    b.Property<int>("LocationLocation__ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitorActivity__DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitorVisitor__ID")
                        .HasColumnType("int");

                    b.HasKey("VisitorActivity__ID");

                    b.HasIndex("LocationLocation__ID");

                    b.HasIndex("VisitorVisitor__ID");

                    b.ToTable("VisitorActivities");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Class", b =>
                {
                    b.HasOne("NCL.Shared.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("Page__ID");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Event", b =>
                {
                    b.HasOne("NCL.Shared.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Class__ID");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Moment", b =>
                {
                    b.HasOne("NCL.Shared.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeEmployee__ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NCL.Shared.Entities.Video", b =>
                {
                    b.HasOne("NCL.Shared.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationLocation__ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NCL.Shared.Entities.VisitorActivity", b =>
                {
                    b.HasOne("NCL.Shared.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationLocation__ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCL.Shared.Entities.Visitor", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorVisitor__ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Visitor");
                });
#pragma warning restore 612, 618
        }
    }
}
